apiVersion: apps/v1
kind: Deployment
metadata: 
  name: python-deployment
  labels:
   app: pythonapk
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pythonapk
  template:
    metadata:
      labels:
        app: pythonapk
    spec:
     containers:
       - name: python
         image: in28min/hello-world-python:0.0.1.RELEASE
         ports:
          - containerPort: 80
          
