apiVersion: apps/v1
kind: Deployment
metadata: 
  name: python-deployment
  labels:
   app: pythonapk
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pythonapk
  template:
    metadata:
      labels:
        app: pythonapk
    spec:
     containers:
       - name: python
         image: in28min/hello-world-python:0.0.1.RELEASE
         ports:
          - containerPort: 80

... 
apiVersion: v1 
kind: Service
metadata:
 name: python-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    python
